Submitted by: <br>
Name: Abraham Chen <br>
ID Number: 12205974 <br>
Course: BS Mathematics with Specialization in Business Applications

# Zomato Exercise

Zomato is a restaurant aggregator website. The platform provides information, menus and user-reviews of restaurants as well as food delivery options from partner restaurants in select cities. You have been provided 3 datasets:

- zomato.csv contains restaurant information like average_cost_for_two, cuisines
- location.csv contains location of the restaurants like address, city, locality & etc
- ratings.csv contains aggregate rating for each restaurant

The different files are connected using the `id` columns which can be found in the different files. The id column is a unique identifier to represent a restaurant. You can use this to **merge** the different files.

In [125]:
import pandas as pd
import numpy as np

1. Merge the zomato, location & ratings file into a signle dataframe and store it to the `merged_df` variable **(3pts)**

Create a DataFrame with zomato.csv:

In [126]:
zomato_df = pd.read_csv("zomato.csv")
zomato_df

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,is_delivering_now,is_table_reservation_supported,is_zomato_book_res,menu_url,mezzo_provider,name,photos_url,price_range,thumb,url
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,0,0,0.0,https://www.zomato.com/manila/mendokoro-ramenb...,OTHER,Mendokoro Ramenba,https://www.zomato.com/manila/mendokoro-ramenb...,3,https://b.zmtcdn.com/data/reviews_photos/971/2...,https://www.zomato.com/manila/mendokoro-ramenb...
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,0,0,0.0,https://www.zomato.com/manila/soban-k-town-gri...,OTHER,Soban K-Town Grill,https://www.zomato.com/manila/soban-k-town-gri...,3,https://b.zmtcdn.com/data/res_imagery/18290970...,https://www.zomato.com/manila/soban-k-town-gri...
2,6307689,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,...,0,0,0.0,https://www.zomato.com/manila/filling-station-...,OTHER,Filling Station,https://www.zomato.com/manila/filling-station-...,4,https://b.zmtcdn.com/data/pictures/9/6307689/b...,https://www.zomato.com/manila/filling-station-...
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,0,0,0.0,https://www.zomato.com/manila/romantic-baboy-t...,OTHER,Romantic Baboy,https://www.zomato.com/manila/romantic-baboy-t...,3,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,https://www.zomato.com/manila/romantic-baboy-t...
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,0,0,0.0,https://www.zomato.com/manila/niu-by-vikings-b...,OTHER,NIU by Vikings,https://www.zomato.com/manila/niu-by-vikings-b...,4,https://b.zmtcdn.com/data/pictures/chains/8/63...,https://www.zomato.com/manila/niu-by-vikings-b...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6825,18635649,1000,NaN,"Deli, Filipino",P,zomato://restaurant/18635649,https://www.zomato.com/manila/trader-juans-fil...,NaN,0,0,...,0,0,0.0,https://www.zomato.com/manila/trader-juans-fil...,OTHER,Trader Juan's,https://www.zomato.com/manila/trader-juans-fil...,3,NaN,https://www.zomato.com/manila/trader-juans-fil...
6826,6318581,400,NaN,Fast Food,P,zomato://restaurant/6318581,https://www.zomato.com/manila/jollibee-north-c...,http://b.zmtcdn.com/data/pictures/chains/0/630...,0,0,...,0,0,0.0,https://www.zomato.com/manila/jollibee-north-c...,OTHER,Jollibee,https://www.zomato.com/manila/jollibee-north-c...,2,https://b.zmtcdn.com/data/pictures/chains/0/63...,https://www.zomato.com/manila/jollibee-north-c...
6827,6318578,450,NaN,"Bakery, Filipino",P,zomato://restaurant/6318578,https://www.zomato.com/manila/goldilocks-north...,https://b.zmtcdn.com/data/res_imagery/6300003_...,0,0,...,0,0,0.0,https://www.zomato.com/manila/goldilocks-north...,OTHER,Goldilocks,https://www.zomato.com/manila/goldilocks-north...,2,https://b.zmtcdn.com/data/res_imagery/6300003_...,https://www.zomato.com/manila/goldilocks-north...
6828,6309612,1000,NaN,"American, Italian",P,zomato://restaurant/6309612,https://www.zomato.com/manila/red-buffalo-wing...,https://b.zmtcdn.com/data/res_imagery/6309612_...,0,0,...,0,0,0.0,https://www.zomato.com/manila/red-buffalo-wing...,OTHER,Red Buffalo Wings & Pizza,https://www.zomato.com/manila/red-buffalo-wing...,3,https://b.zmtcdn.com/data/res_imagery/6309612_...,https://www.zomato.com/manila/red-buffalo-wing...
6829,6318582,600,NaN,"Pizza, Fast Food",P,zomato://restaurant/6318582,https://www.zomato.com/manila/greenwich-north-...,https://b.zmtcdn.com/data/pictures/chains/2/63...,0,0,...,0,0,0.0,https://www.zomato.com/manila/greenwich-north-...,OTHER,Greenwich,https://www.zomato.com/manila/greenwich-north-...,2,https://b.zmtcdn.com/data/pictures/chains/2/63...,https://www.zomato.com/manila/greenwich-north-...

Create a DataFrame with ratings.csv:

In [127]:
ratings_df = pd.read_csv("ratings.csv")
ratings_df

            id  aggregate_rating rating_color rating_text  votes
0      6316125               4.9       3F7E00   Excellent   1394
1     18409457               4.6       3F7E00   Excellent    602
2      6307689               4.0       5BA829   Very Good    563
3     18581637               4.0       5BA829   Very Good    413
4      6315438               4.6       3F7E00   Excellent    960
...        ...               ...          ...         ...    ...
6825  18635649               2.9       FFBA00     Average      6
6826   6318581               3.0       CDD614     Average      5
6827   6318578               0.0       CBCBC8   Not rated      1
6828   6309612               3.7       9ACD32        Good     96
6829   6318582               0.0       CBCBC8   Not rated      2

[6830 rows x 5 columns]

Create a DataFrame with location.csv:

In [128]:
location_df = pd.read_csv("location.csv")
location_df

,id,address,city,city_id,country_id,latitude,locality,locality_verbose,longitude,zipcode
0,6316125,"V. Corporate Center, Soliman Street, Salcedo V...",Makati City,63,162,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN
1,18409457,"Level 3, Greenbelt 3, Ayala Center, Greenbelt,...",Makati City,63,162,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN
2,6307689,"5012 P. Burgos Street, Poblacion, Makati City ...",Makati City,63,162,14.563144,Poblacion,"Poblacion, Makati City",121.029800,1210.0
3,18581637,"CKB Centre, Tomas Morato Avenue Corner Scout R...",Quezon City,63,162,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN
4,6315438,"Sixth Floor, SM Aura Premier, C5 Road Corner 2...",Taguig City,63,162,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN
...,...,...,...,...,...,...,...,...,...,...
6825,18635649,"Westgate Center, Filinvest City, Muntinlupa City",Muntinlupa City,63,162,14.422261,"Westgate Center, Filinvest City, Mutinlupa City","Westgate Center, Filinvest City, Mutinlupa Cit...",121.033175,NaN
6826,6318581,"Zabarte Town Center, Zabarte Corner Camarin Ro...",Caloocan City,63,162,14.756424,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043329,NaN
6827,6318578,"Zabarte Town Center, Zabarte Corner Camarin Ro...",Caloocan City,63,162,14.756406,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043498,NaN
6828,6309612,"Greenhills Town Center, Granada Street, Valenc...",Quezon City,63,162,14.610628,"Greenhills Town Center, Valencia, Quezon City","Greenhills Town Center, Valencia, Quezon City ...",121.037031,NaN
6829,6318582,"Ground Floor, Zabarte Town Center, Zabarte Cor...",Caloocan City,63,162,14.756382,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043452,NaN

Merge the three DataFrames together:

In [129]:
merged_df = zomato_df.merge(location_df, on="id").merge(ratings_df, on="id")
merged_df

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,country_id,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,162,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN,4.9,3F7E00,Excellent,1394
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,162,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN,4.6,3F7E00,Excellent,602
2,6307689,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,...,162,14.563144,Poblacion,"Poblacion, Makati City",121.029800,1210.0,4.0,5BA829,Very Good,563
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,162,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN,4.0,5BA829,Very Good,413
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,162,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN,4.6,3F7E00,Excellent,960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6825,18635649,1000,NaN,"Deli, Filipino",P,zomato://restaurant/18635649,https://www.zomato.com/manila/trader-juans-fil...,NaN,0,0,...,162,14.422261,"Westgate Center, Filinvest City, Mutinlupa City","Westgate Center, Filinvest City, Mutinlupa Cit...",121.033175,NaN,2.9,FFBA00,Average,6
6826,6318581,400,NaN,Fast Food,P,zomato://restaurant/6318581,https://www.zomato.com/manila/jollibee-north-c...,http://b.zmtcdn.com/data/pictures/chains/0/630...,0,0,...,162,14.756424,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043329,NaN,3.0,CDD614,Average,5
6827,6318578,450,NaN,"Bakery, Filipino",P,zomato://restaurant/6318578,https://www.zomato.com/manila/goldilocks-north...,https://b.zmtcdn.com/data/res_imagery/6300003_...,0,0,...,162,14.756406,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043498,NaN,0.0,CBCBC8,Not rated,1
6828,6309612,1000,NaN,"American, Italian",P,zomato://restaurant/6309612,https://www.zomato.com/manila/red-buffalo-wing...,https://b.zmtcdn.com/data/res_imagery/6309612_...,0,0,...,162,14.610628,"Greenhills Town Center, Valencia, Quezon City","Greenhills Town Center, Valencia, Quezon City ...",121.037031,NaN,3.7,9ACD32,Good,96
6829,6318582,600,NaN,"Pizza, Fast Food",P,zomato://restaurant/6318582,https://www.zomato.com/manila/greenwich-north-...,https://b.zmtcdn.com/data/pictures/chains/2/63...,0,0,...,162,14.756382,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043452,NaN,0.0,CBCBC8,Not rated,2

In [130]:
assert (6830, 35)==merged_df.shape

cols = ['id', 'address', 'city', 'city_id', 'country_id', 'latitude',
       'locality', 'locality_verbose', 'longitude', 'zipcode',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view',
       'is_delivering_now', 'is_table_reservation_supported',
       'is_zomato_book_res', 'menu_url', 'mezzo_provider', 'name',
       'photos_url', 'price_range', 'thumb', 'url']

assert sorted(merged_df.columns) == sorted(cols)

2. Create a function that returns the average aggregate rating for each city. Expected returned value is a Series datatype which contains name of city as index and average aggregate rating as value. **(2pts)**

In [131]:
def exercise_2(merged_df):
    return merged_df.groupby("city")["aggregate_rating"].agg("mean")

In [132]:
merged_df.groupby("city")["aggregate_rating"].agg("mean")

city
Caloocan City       1.953509
Las Piñas City      2.855738
Makati City         3.250512
Malabon City        1.558333
Mandaluyong City    2.951919
Manila              2.842652
Marikina City       2.672512
Muntinlupa City     2.962682
Parañaque City      3.130100
Pasay City          3.302075
Pasig City          2.916086
Pateros City        1.740000
Quezon City         2.887946
San Juan City       3.098462
Tagaytay City       2.959259
Taguig City         3.234105
Valenzuela City     1.890741
Name: aggregate_rating, dtype: float64

In [133]:
res_series = exercise_2(merged_df)
assert True == np.isclose(3.302075, res_series[res_series.index == 'Pasay City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.890741, res_series[res_series.index == 'Valenzuela City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.558333, res_series[res_series.index == 'Malabon City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]

3. Using the apply function of pandas convert the rating_text to a numeric equivalent. You are to introduce a new column in merged_df called `rating_numeric` which is based on the value from rating_text: **(3pts)**

Excellent = 5 <br>
Very Good = 4 <br>
Good = 3 <br>
Average = 2 <br>
Poor = 1 <br>
Not rated = 0 <br>

In [134]:
rating_dict = {"Excellent":5, "Very Good":4, "Good":3, "Average":2, "Poor":1, "Not rated":0}
merged_df["rating_numeric"] = merged_df["rating_text"].apply(lambda x: rating_dict.get(x))
merged_df[["name", "rating_numeric", "rating_text"]]

                           name  rating_numeric rating_text
0             Mendokoro Ramenba               5   Excellent
1            Soban K-Town Grill               5   Excellent
2               Filling Station               4   Very Good
3                Romantic Baboy               4   Very Good
4                NIU by Vikings               5   Excellent
...                         ...             ...         ...
6825              Trader Juan's               2     Average
6826                   Jollibee               2     Average
6827                 Goldilocks               0   Not rated
6828  Red Buffalo Wings & Pizza               3        Good
6829                  Greenwich               0   Not rated

[6830 rows x 3 columns]

In [135]:
assert 868 == merged_df[merged_df.rating_numeric == 0].shape[0]
assert True == ('rating_numeric' in merged_df.columns)

4. Create a function which filters the merged dataframe to only contain rows coming in from a specific city. Expected returned value is a dataframe **(2pts)**

In [136]:
merged_df
def exercise_4(merged_df, city):
    return merged_df[merged_df["city"] == city]

In [137]:
assert 'Makati City' == exercise_4(merged_df, 'Makati City').city.unique()[0]
assert (976, 36) == exercise_4(merged_df, 'Makati City').shape

assert 'Mandaluyong City' == exercise_4(merged_df, 'Mandaluyong City').city.unique()[0]
assert (443, 36) == exercise_4(merged_df, 'Mandaluyong City').shape

assert (0, 36) == exercise_4(merged_df, 'Quezon  City').shape

5. Create a function to filter the dataframe to only contain certain columns passed in the function. Expected returned value is a dataframe **(1pt)**

In [138]:
merged_df
def exercise_5(merged_df, cols_to_filter):
    return merged_df[cols_to_filter]

In [139]:
cols = ['name', 'cuisines', 'city', 'aggregate_rating']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 4) == exercise_5(merged_df, cols).shape

cols = ['average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 11) == exercise_5(merged_df, cols).shape

6.  What is the most common restaurant name in the dataset? **(2pts)** Write down your answer and show code used to come up with the answer.

In [140]:
merged_df.value_counts("name")

name
Starbucks                         99
Jollibee                          77
McDonald's                        66
KFC                               54
BonChon Chicken                   49
                                  ..
HotBox Kitchen                     1
Hotel Bar                          1
Hotties Gourmet                    1
House Manila - Remington Hotel     1
¡VENGO!                            1
Name: count, Length: 3286, dtype: int64

The most common restaurant name is Starbucks, with 99 occurrences.

7. Which restaurant has the most expensive average cost for two? **(2pts)** Write down your answer and show code used to come up with the answer.

In [141]:
merged_df[["name","average_cost_for_two"]].sort_values(by="average_cost_for_two", ascending=False)

                                           name  average_cost_for_two
1713                           The Tasting Room                 10000
5      Spiral - Sofitel Philippine Plaza Manila                  6000
1728               Medley Buffet - Okada Manila                  5400
1750  Wolfgang's Steakhouse by Wolfgang Zwiener                  5100
2039  Wolfgang's Steakhouse by Wolfgang Zwiener                  5100
...                                         ...                   ...
6796                           Katherine's Cafe                     0
4714                            The Baking Crew                     0
6482                                   Toritake                     0
6192                                  Sari Salo                     0
6509                                   KapeTayo                     0

[6830 rows x 2 columns]

The restaurant with the most expensive average cost for two is The Tasting Room at 10,000 pesos.

8. How many restaurants do not have a zipcode? **(1pt)** Write down your answer and show code used to come up with the answer.

In [142]:
merged_df[merged_df["zipcode"].isna()]

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes,rating_numeric
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN,4.9,3F7E00,Excellent,1394,5
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN,4.6,3F7E00,Excellent,602,5
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN,4.0,5BA829,Very Good,413,4
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN,4.6,3F7E00,Excellent,960,5
5,6300010,6000,NaN,"European, Asian, Indian",P,zomato://restaurant/6300010,https://www.zomato.com/manila/spiral-sofitel-p...,https://b.zmtcdn.com/data/res_imagery/6300010_...,0,0,...,14.553256,"Sofitel Philippine Plaza Manila, CCP Complex, ...","Sofitel Philippine Plaza Manila, CCP Complex, ...",120.981510,NaN,4.9,3F7E00,Excellent,1014,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6825,18635649,1000,NaN,"Deli, Filipino",P,zomato://restaurant/18635649,https://www.zomato.com/manila/trader-juans-fil...,NaN,0,0,...,14.422261,"Westgate Center, Filinvest City, Mutinlupa City","Westgate Center, Filinvest City, Mutinlupa Cit...",121.033175,NaN,2.9,FFBA00,Average,6,2
6826,6318581,400,NaN,Fast Food,P,zomato://restaurant/6318581,https://www.zomato.com/manila/jollibee-north-c...,http://b.zmtcdn.com/data/pictures/chains/0/630...,0,0,...,14.756424,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043329,NaN,3.0,CDD614,Average,5,2
6827,6318578,450,NaN,"Bakery, Filipino",P,zomato://restaurant/6318578,https://www.zomato.com/manila/goldilocks-north...,https://b.zmtcdn.com/data/res_imagery/6300003_...,0,0,...,14.756406,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043498,NaN,0.0,CBCBC8,Not rated,1,0
6828,6309612,1000,NaN,"American, Italian",P,zomato://restaurant/6309612,https://www.zomato.com/manila/red-buffalo-wing...,https://b.zmtcdn.com/data/res_imagery/6309612_...,0,0,...,14.610628,"Greenhills Town Center, Valencia, Quezon City","Greenhills Town Center, Valencia, Quezon City ...",121.037031,NaN,3.7,9ACD32,Good,96,3
6829,6318582,600,NaN,"Pizza, Fast Food",P,zomato://restaurant/6318582,https://www.zomato.com/manila/greenwich-north-...,https://b.zmtcdn.com/data/pictures/chains/2/63...,0,0,...,14.756382,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043452,NaN,0.0,CBCBC8,Not rated,2,0

There are 6713 restaurants without a zipcode.

9. How many restaurants in the dataset allow online delivery? **(1pt)** Write down your answer and show code used to come up with the answer.

In [143]:
merged_df[merged_df["has_online_delivery"] == 1]

Empty DataFrame
Columns: [id, average_cost_for_two, book_url, cuisines, currency, deeplink, events_url, featured_image, has_online_delivery, has_table_booking, include_bogo_offers, is_book_form_web_view, is_delivering_now, is_table_reservation_supported, is_zomato_book_res, menu_url, mezzo_provider, name, photos_url, price_range, thumb, url, address, city, city_id, country_id, latitude, locality, locality_verbose, longitude, zipcode, aggregate_rating, rating_color, rating_text, votes, rating_numeric]
Index: []

[0 rows x 36 columns]

No restaurants support online delivery (sad!)

10. Which locality has more expensive food? Poblacion or Salcedo Village? **(3pts)** Write down your answer and show code used to come up with the answer.

In [144]:
pobla_salcedo_filter = merged_df[(merged_df["locality"] == "Poblacion") | (merged_df["locality"] == "Salcedo Village")]
pobla_salcedo_filter.groupby("locality")["average_cost_for_two"].agg("mean")

locality
Poblacion          898.214286
Salcedo Village    989.102564
Name: average_cost_for_two, dtype: float64

Salcedo Village has the more expensive food, where the aggregate average cost for two is 989.10 pesos.